spring:
  application:
    name: flow-prod

  config:
    import:
      - file:env/prod.env[.properties]

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 30MB

logging:
  level:
    root: INFO
    org:
      springframework:
        web: ERROR

oauth2:
  base-url: ${OAUTH2_BASE_URL}
  client-name: ${OAUTH2_CLIENT_NAME}
  client-id: ${OAUTH2_CLIENT_ID}
  client-secret: ${OAUTH2_CLIENT_SECRET}
  authorization-grant-type: ${OAUTH2_GRANT_TYPE}
  client-authentication-method: ${OAUTH2_AUTH_METHOD}
  redirect-uri: ${OAUTH2_REDIRECT_URL}
  scope:
    - profile_nickname
    - profile_image
    - account_email
